title: Software Dev Blog
subtitle: ""
description: "by Ash Grennan - Software Developer based in Burnley."
author: Ash Grennan
language: en
timezone: UTC

url: https://hexo.io
root: /
permalink: post/:title/
archive_dir: posts
code_dir: downloads/code
new_post_name: :title.md # File name of new posts
post_asset_folder: true

theme: flexy

highlight:
  enable: true
  line_number: false

disqus_shortname: https-ashgrennan-com
google_analytics: UA-48498357-3
twitter: ashgrennan
github: bobnudd

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page